name = "urcl-ld"
version = "1.0.0"
license = "MIT"
author = "Verlio H"
maintainer = "verlioh0@gmail.com"
copyright = "Copyright 2024, Oliver Hines"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
